@SET WIRESHARKVERSION=1.4.4
@SET WIRESHARKINSTALLDIR=C:\Program Files\Wireshark
@SET WIRESHARKDEFINITIONSDIR=D:\workspace\converter\install\asterix

cp %WIRESHARKDEFINITIONSDIR%/asterix*.xml "%WIRESHARKINSTALLDIR%\plugins\%WIRESHARKVERSION%"
cp %WIRESHARKDEFINITIONSDIR%/asterix.ini "%WIRESHARKINSTALLDIR%\plugins\%WIRESHARKVERSION%"
